// DO NOT EDIT — generated by `cargo run --bin gen_rules_ts > www/src/data/rules.ts`.
// Source of truth: the Rust rule registry in `src/rules/mod.rs`.
// To add or update rules, edit the Rust source and regenerate this file.

export interface Rule {
  id: string;
  cwe: string;
  desc: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
}

export interface RuleGroup {
  name: string;
  slug: string;
  rules: Rule[];
}

const jsRules: Rule[] = [
  { id: 'js/express-cookie-no-httponly', cwe: 'CWE-1004', desc: 'Cookie configuration missing httpOnly flag', severity: 'medium' },
  { id: 'js/express-cookie-no-samesite', cwe: 'CWE-352', desc: 'Cookie configuration missing sameSite protection', severity: 'medium' },
  { id: 'js/express-cookie-no-secure', cwe: 'CWE-614', desc: 'Cookie configuration missing secure flag', severity: 'medium' },
  { id: 'js/express-direct-response-write', cwe: 'CWE-79', desc: 'XSS via direct response write with user input', severity: 'high' },
  { id: 'js/express-no-hardcoded-session-secret', cwe: 'CWE-798', desc: 'Hardcoded session secret in express-session configuration', severity: 'high' },
  { id: 'js/express-session-resave-true', cwe: 'CWE-384', desc: 'express-session configured with resave: true', severity: 'medium' },
  { id: 'js/express-session-saveuninitialized-true', cwe: 'CWE-359', desc: 'express-session configured with saveUninitialized: true', severity: 'medium' },
  { id: 'js/jwt-decode-without-verify', cwe: 'CWE-347', desc: 'JWT decoded without signature verification', severity: 'high' },
  { id: 'js/jwt-hardcoded-secret', cwe: 'CWE-798', desc: 'JWT signing or verification with a hardcoded secret', severity: 'high' },
  { id: 'js/jwt-ignore-expiration', cwe: 'CWE-613', desc: 'JWT verification configured to ignore token expiration', severity: 'high' },
  { id: 'js/jwt-none-algorithm', cwe: 'CWE-347', desc: 'JWT configured to use the \'none\' algorithm', severity: 'high' },
  { id: 'js/jwt-verify-missing-algorithms', cwe: 'CWE-347', desc: 'JWT verification without an explicit algorithms allowlist', severity: 'high' },
  { id: 'js/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via exec/spawn with dynamic input', severity: 'critical' },
  { id: 'js/no-cors-star', cwe: 'CWE-942', desc: 'CORS misconfiguration allowing all origins', severity: 'medium' },
  { id: 'js/no-document-write', cwe: 'CWE-79', desc: 'document.write() can lead to XSS vulnerabilities', severity: 'high' },
  { id: 'js/no-eval', cwe: 'CWE-95', desc: 'Use of eval() allows arbitrary code execution', severity: 'critical' },
  { id: 'js/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'js/no-open-redirect', cwe: 'CWE-601', desc: 'Open redirect via assignment to window.location with user input', severity: 'medium' },
  { id: 'js/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via fs operations with user input', severity: 'high' },
  { id: 'js/no-prototype-pollution', cwe: 'CWE-1321', desc: 'Potential prototype pollution via dynamic property assignment', severity: 'high' },
  { id: 'js/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string concatenation or template literal', severity: 'critical' },
  { id: 'js/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via dynamic outbound request URL', severity: 'high' },
  { id: 'js/no-unsafe-format-string', cwe: 'CWE-134', desc: 'Template literal with variables in console/logging function may enable log injection', severity: 'medium' },
  { id: 'js/no-unsafe-regex', cwe: 'CWE-1333', desc: 'Potentially catastrophic backtracking regex pattern', severity: 'medium' },
  { id: 'js/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
  { id: 'js/no-xss-innerhtml', cwe: 'CWE-79', desc: 'Assignment to innerHTML may lead to XSS', severity: 'high' },
  { id: 'js/taint-sql-injection', cwe: 'CWE-89', desc: 'Untrusted input reaches a SQL execute sink — possible SQL injection', severity: 'critical' },
  { id: 'js/taint-xss-innerhtml', cwe: 'CWE-79', desc: 'Untrusted input reaches innerHTML or document.write sink', severity: 'high' },
];

const pyRules: Rule[] = [
  { id: 'py/csrf-cookie-httponly-disabled', cwe: 'CWE-1004', desc: 'CSRF_COOKIE_HTTPONLY disabled in source code', severity: 'medium' },
  { id: 'py/csrf-cookie-samesite-disabled', cwe: 'CWE-352', desc: 'CSRF_COOKIE_SAMESITE disabled in source code', severity: 'medium' },
  { id: 'py/csrf-cookie-secure-disabled', cwe: 'CWE-614', desc: 'CSRF_COOKIE_SECURE disabled in source code', severity: 'medium' },
  { id: 'py/csrf-exempt', cwe: 'CWE-352', desc: 'View marked csrf_exempt', severity: 'high' },
  { id: 'py/django-allowed-hosts-wildcard', cwe: 'CWE-346', desc: 'Django ALLOWED_HOSTS allows all hosts', severity: 'medium' },
  { id: 'py/django-secret-key-hardcoded', cwe: 'CWE-798', desc: 'Django SECRET_KEY hardcoded in source code', severity: 'high' },
  { id: 'py/flask-debug-mode', cwe: 'CWE-489', desc: 'Flask app.run(debug=True) exposes debugger and reloader in production', severity: 'high' },
  { id: 'py/flask-secret-key-hardcoded', cwe: 'CWE-798', desc: 'Flask SECRET_KEY hardcoded in source code', severity: 'high' },
  { id: 'py/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via os.system/subprocess with user input', severity: 'critical' },
  { id: 'py/no-cors-star', cwe: 'CWE-942', desc: 'CORS misconfiguration allowing all origins', severity: 'medium' },
  { id: 'py/no-debug-true', cwe: 'CWE-489', desc: 'DEBUG = True left enabled — disable in production', severity: 'medium' },
  { id: 'py/no-eval', cwe: 'CWE-95', desc: 'Use of eval()/exec() allows arbitrary code execution', severity: 'critical' },
  { id: 'py/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'py/no-open-redirect', cwe: 'CWE-601', desc: 'Open redirect via redirect() with user-controlled input', severity: 'medium' },
  { id: 'py/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via open() with user input', severity: 'high' },
  { id: 'py/no-pickle', cwe: 'CWE-502', desc: 'Deserialization of untrusted data via pickle', severity: 'high' },
  { id: 'py/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string formatting', severity: 'critical' },
  { id: 'py/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via dynamic outbound request URL', severity: 'high' },
  { id: 'py/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
  { id: 'py/no-yaml-load', cwe: 'CWE-502', desc: 'yaml.load() without SafeLoader can execute arbitrary code', severity: 'high' },
  { id: 'py/secure-ssl-redirect-disabled', cwe: 'CWE-319', desc: 'Django SECURE_SSL_REDIRECT disabled in source code', severity: 'medium' },
  { id: 'py/session-cookie-httponly-disabled', cwe: 'CWE-1004', desc: 'SESSION_COOKIE_HTTPONLY disabled in source code', severity: 'medium' },
  { id: 'py/session-cookie-samesite-disabled', cwe: 'CWE-352', desc: 'SESSION_COOKIE_SAMESITE disabled in source code', severity: 'medium' },
  { id: 'py/session-cookie-secure-disabled', cwe: 'CWE-614', desc: 'SESSION_COOKIE_SECURE disabled in source code', severity: 'medium' },
  { id: 'py/taint-command-injection', cwe: 'CWE-78', desc: 'Untrusted input reaches OS command execution sink', severity: 'critical' },
  { id: 'py/taint-eval', cwe: 'CWE-95', desc: 'Untrusted input reaches eval/exec sink', severity: 'critical' },
  { id: 'py/taint-pickle-deserialization', cwe: 'CWE-502', desc: 'Untrusted input reaches pickle deserialization sink', severity: 'critical' },
  { id: 'py/taint-sql-injection', cwe: 'CWE-89', desc: 'Untrusted input reaches DB execute sink', severity: 'critical' },
  { id: 'py/taint-ssrf', cwe: 'CWE-918', desc: 'Untrusted input reaches outbound HTTP sink (potential SSRF)', severity: 'high' },
  { id: 'py/taint-yaml-load', cwe: 'CWE-502', desc: 'Untrusted input reaches unsafe YAML loader', severity: 'critical' },
  { id: 'py/wtf-csrf-check-default-disabled', cwe: 'CWE-352', desc: 'Flask-WTF default CSRF checks disabled in source code', severity: 'high' },
  { id: 'py/wtf-csrf-disabled', cwe: 'CWE-352', desc: 'Flask-WTF CSRF protection disabled in source code', severity: 'high' },
];

const goRules: Rule[] = [
  { id: 'go/gin-no-trusted-proxies', cwe: 'CWE-346', desc: 'Gin engine created without SetTrustedProxies configuration', severity: 'medium' },
  { id: 'go/insecure-tls-skip-verify', cwe: 'CWE-295', desc: 'TLS certificate verification disabled with InsecureSkipVerify', severity: 'high' },
  { id: 'go/net-http-no-timeout', cwe: 'CWE-400', desc: 'http.ListenAndServe without timeout configuration enables slowloris attacks', severity: 'medium' },
  { id: 'go/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via exec.Command with dynamic input', severity: 'critical' },
  { id: 'go/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'go/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string concatenation or fmt.Sprintf', severity: 'critical' },
  { id: 'go/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via http.Get/http.Post with variable URL', severity: 'high' },
  { id: 'go/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
  { id: 'go/taint-command-injection', cwe: 'CWE-78', desc: 'Untrusted input reaches os/exec command execution sink', severity: 'critical' },
  { id: 'go/taint-sql-injection', cwe: 'CWE-89', desc: 'Untrusted input reaches database Query/Exec sink', severity: 'critical' },
  { id: 'go/taint-ssrf', cwe: 'CWE-918', desc: 'Untrusted input reaches outbound net/http sink (potential SSRF)', severity: 'high' },
];

const rubyRules: Rule[] = [
  { id: 'rb/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via system/exec/spawn or backtick execution', severity: 'critical' },
  { id: 'rb/no-csrf-skip', cwe: 'CWE-352', desc: 'CSRF protection disabled via skip_before_action', severity: 'high' },
  { id: 'rb/no-eval', cwe: 'CWE-95', desc: 'Use of eval or similar dynamic code execution', severity: 'critical' },
  { id: 'rb/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'rb/no-html-safe', cwe: 'CWE-79', desc: 'Potential XSS via html_safe or raw()', severity: 'high' },
  { id: 'rb/no-mass-assignment', cwe: 'CWE-915', desc: 'Mass assignment via permit! allows all parameters', severity: 'high' },
  { id: 'rb/no-open-redirect', cwe: 'CWE-601', desc: 'Potential open redirect via redirect_to with dynamic argument', severity: 'high' },
  { id: 'rb/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string interpolation in query methods', severity: 'critical' },
  { id: 'rb/no-unsafe-deserialization', cwe: 'CWE-502', desc: 'Unsafe deserialization via Marshal.load or YAML.load', severity: 'critical' },
  { id: 'rb/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
];

const javaRules: Rule[] = [
  { id: 'java/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via Runtime.exec or ProcessBuilder with dynamic input', severity: 'critical' },
  { id: 'java/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'java/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via dynamic file path', severity: 'high' },
  { id: 'java/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string concatenation in query method', severity: 'critical' },
  { id: 'java/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via URL or RestTemplate with dynamic input', severity: 'high' },
  { id: 'java/no-unsafe-deserialization', cwe: 'CWE-502', desc: 'Unsafe deserialization can lead to remote code execution', severity: 'critical' },
  { id: 'java/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic algorithm', severity: 'medium' },
  { id: 'java/no-xxe', cwe: 'CWE-611', desc: 'XML parser created without disabling external entities (XXE)', severity: 'high' },
  { id: 'java/spring-cors-permissive', cwe: 'CWE-942', desc: 'Permissive CORS configuration allows any origin', severity: 'medium' },
  { id: 'java/spring-csrf-disabled', cwe: 'CWE-352', desc: 'Spring Security CSRF protection is disabled', severity: 'high' },
];

const phpRules: Rule[] = [
  { id: 'php/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via shell execution function', severity: 'critical' },
  { id: 'php/no-eval', cwe: 'CWE-95', desc: 'Use of eval() allows arbitrary code execution', severity: 'critical' },
  { id: 'php/no-extract', cwe: 'CWE-621', desc: 'Use of extract() can overwrite existing variables', severity: 'high' },
  { id: 'php/no-file-inclusion', cwe: 'CWE-98', desc: 'Dynamic file inclusion with variable argument enables remote/local file inclusion', severity: 'critical' },
  { id: 'php/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'php/no-preg-eval', cwe: 'CWE-95', desc: 'preg_replace with /e modifier allows arbitrary code execution', severity: 'critical' },
  { id: 'php/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string interpolation or concatenation', severity: 'critical' },
  { id: 'php/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via file_get_contents or curl_init with variable URL', severity: 'high' },
  { id: 'php/no-unserialize', cwe: 'CWE-502', desc: 'Use of unserialize() on untrusted data can lead to object injection', severity: 'critical' },
  { id: 'php/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
];

const rustRules: Rule[] = [
  { id: 'rs/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via Command::new with dynamic input', severity: 'critical' },
  { id: 'rs/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'rs/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via Path::new or PathBuf::from with dynamic input', severity: 'medium' },
  { id: 'rs/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via format! macro in query argument', severity: 'critical' },
  { id: 'rs/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via reqwest with dynamic URL', severity: 'high' },
  { id: 'rs/no-unwrap-in-lib', cwe: 'CWE-248', desc: 'Use of .unwrap() or .expect() can cause panics in production', severity: 'medium' },
  { id: 'rs/no-weak-hash', cwe: 'CWE-328', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
  { id: 'rs/tls-verify-disabled', cwe: 'CWE-295', desc: 'TLS certificate verification disabled with danger_accept_invalid_certs', severity: 'high' },
  { id: 'rs/transmute-usage', cwe: 'CWE-843', desc: 'Use of std::mem::transmute can cause type confusion and undefined behavior', severity: 'high' },
  { id: 'rs/unsafe-block', cwe: 'CWE-676', desc: 'Use of unsafe block bypasses Rust memory safety guarantees', severity: 'medium' },
];

const csharpRules: Rule[] = [
  { id: 'cs/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via Process.Start with dynamic argument', severity: 'critical' },
  { id: 'cs/no-cors-star', cwe: 'CWE-942', desc: 'Overly permissive CORS configuration', severity: 'medium' },
  { id: 'cs/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'cs/no-ldap-injection', cwe: 'CWE-90', desc: 'Potential LDAP injection via string concatenation in search filter', severity: 'high' },
  { id: 'cs/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via dynamic file path', severity: 'high' },
  { id: 'cs/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string concatenation in database call', severity: 'critical' },
  { id: 'cs/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via HTTP request with dynamic URL', severity: 'high' },
  { id: 'cs/no-unsafe-deserialization', cwe: 'CWE-502', desc: 'Use of unsafe deserialization API', severity: 'critical' },
  { id: 'cs/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic algorithm', severity: 'medium' },
  { id: 'cs/no-xxe', cwe: 'CWE-611', desc: 'Potential XXE vulnerability in XML parsing', severity: 'high' },
];

const swiftRules: Rule[] = [
  { id: 'swift/no-command-injection', cwe: 'CWE-78', desc: 'Potential command injection via Process or NSTask with dynamic arguments', severity: 'critical' },
  { id: 'swift/no-eval-js', cwe: 'CWE-95', desc: 'WKWebView evaluateJavaScript with dynamic input enables code injection', severity: 'critical' },
  { id: 'swift/no-hardcoded-secret', cwe: 'CWE-798', desc: 'Hardcoded secret or credential detected', severity: 'high' },
  { id: 'swift/no-insecure-keychain', cwe: 'CWE-311', desc: 'Insecure Keychain accessibility level allows access when device is locked', severity: 'high' },
  { id: 'swift/no-insecure-transport', cwe: 'CWE-319', desc: 'Insecure HTTP URL detected — use HTTPS instead', severity: 'high' },
  { id: 'swift/no-path-traversal', cwe: 'CWE-22', desc: 'Potential path traversal via FileManager with dynamic path', severity: 'high' },
  { id: 'swift/no-sql-injection', cwe: 'CWE-89', desc: 'Potential SQL injection via string interpolation in SQLite queries', severity: 'critical' },
  { id: 'swift/no-ssrf', cwe: 'CWE-918', desc: 'Potential SSRF via URLSession or URL with dynamic input', severity: 'high' },
  { id: 'swift/no-tls-disabled', cwe: 'CWE-295', desc: 'TLS certificate validation disabled or weakened', severity: 'high' },
  { id: 'swift/no-weak-crypto', cwe: 'CWE-327', desc: 'Use of weak cryptographic hash (MD5/SHA1)', severity: 'medium' },
];

export const ruleGroups: RuleGroup[] = [
  { name: 'JavaScript / TypeScript', slug: 'js', rules: jsRules },
  { name: 'Python', slug: 'py', rules: pyRules },
  { name: 'Go', slug: 'go', rules: goRules },
  { name: 'Ruby', slug: 'rb', rules: rubyRules },
  { name: 'Java', slug: 'java', rules: javaRules },
  { name: 'PHP', slug: 'php', rules: phpRules },
  { name: 'Rust', slug: 'rs', rules: rustRules },
  { name: 'C#', slug: 'cs', rules: csharpRules },
  { name: 'Swift', slug: 'swift', rules: swiftRules },
];

export const totalRules = ruleGroups.reduce((sum, g) => sum + g.rules.length, 0);
export const productLanguageCount = 9;
